
-- Script SQL para el Sistema de Gestión de Inventario (Oracle APEX)

-- Tabla de roles
CREATE TABLE ROL (
    ID_ROL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ROL VARCHAR2(50) NOT NULL UNIQUE
);

-- Tabla de empleados
CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_ROL NUMBER NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

-- Tabla de áreas
CREATE TABLE AREA (
    ID_AREA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_AREA VARCHAR2(50) NOT NULL UNIQUE,
    ID_JEFE NUMBER,
    FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADO(ID_EMPLEADO)
);

-- Asociación de empleados con áreas
CREATE TABLE EMPLEADO_AREA (
    ID_EMPLEADO NUMBER,
    ID_AREA NUMBER,
    PRIMARY KEY (ID_EMPLEADO, ID_AREA),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY (ID_AREA) REFERENCES AREA(ID_AREA)
);

-- Tabla de sucursales
CREATE TABLE SUCURSAL (
    ID_SUCURSAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CIUDAD VARCHAR2(100)
);

-- Gerente externo (no empleado del negocio)
CREATE TABLE GERENTE_SUCURSAL (
    ID_GERENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_SUCURSAL NUMBER UNIQUE NOT NULL,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

-- Tabla de materiales
CREATE TABLE MATERIAL (
    ID_MATERIAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255),
    CATEGORIA VARCHAR2(50),
    UNIDAD_PRESENTACION VARCHAR2(50),
    CANTIDAD_POR_PRESENTACION NUMBER,
    COSTO_UNITARIO NUMBER(10,2) NOT NULL
);

-- Tabla de arribos de material
CREATE TABLE ARRIBO_MATERIAL (
    ID_ARRIBO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MATERIAL NUMBER NOT NULL,
    ID_ENCARGADO NUMBER NOT NULL,
    CANTIDAD_PRESENTACIONES NUMBER NOT NULL,
    FECHA_ARRIBO DATE DEFAULT SYSDATE,
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL),
    FOREIGN KEY (ID_ENCARGADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

-- Tabla de uso de materiales en sucursal
CREATE TABLE USO_MATERIAL (
    ID_USO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_MATERIAL NUMBER NOT NULL,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_SUCURSAL NUMBER NOT NULL,
    CANTIDAD_UTILIZADA NUMBER NOT NULL,
    FECHA_USO DATE DEFAULT SYSDATE,
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

-- Tabla de inventario actual
CREATE TABLE INVENTARIO_ACTUAL (
    ID_MATERIAL NUMBER PRIMARY KEY,
    UNIDADES_DISPONIBLES NUMBER DEFAULT 0,
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL)
);
